name: JobFinder CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v3

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: 3. Instalar Dependências
        run: npm install

      - name: 4. Deploy para o Ambiente de Staging
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}