name: JobFinder CI Pipeline

on:
  pull_request:
    branches:
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    services: 
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v3 

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' 
          cache: 'npm' 

      - name: 3. Instalar Dependências
        run: npm install

      - name: 4. Executar Testes Automatizados
        run: npm test
        env: 
          MONGO_URI: mongodb://mongodb:27017/jobfinder-test
          SESSION_SECRET: ${{secrets.SECRET}} 
          

      - name: 5. Verificar Build (se aplicável)
        run: npm run build --if-present

