name: JobFinder CI Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3 

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' 
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Instalar Dependências
        run: npm install
        working-directory: ./backend

      - name: Executar Testes Automatizados
        run: npm test
        working-directory: ./backend
        env: 
          SESSION_SECRET: ${{secrets.SESSION_SECRET}} 

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    needs: frontend-test

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instalar Dependências
        run: npm install
        working-directory: ./frontend

      - name: Build do Frontend
        run: npm run build
        working-directory: ./frontend

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instalar Dependências
        run: npm install
        working-directory: ./frontend

      - name: Executar Testes do Frontend
        run: npm test
        working-directory: ./frontend
